services:
  # Application
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: gabcat/csguild-server:latest
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
